"""
AITHORIX Strategy Coordinator
Manages trading strategies and signal generation

This module coordinates all trading strategies including:
- Strategy lifecycle management
- Signal generation and validation
- Strategy performance tracking
- Multi-strategy coordination
"""

import asyncio
import logging
from typing import Dict, List, Optional, Any, Set, Callable, Tuple
from datetime import datetime, timedelta
from decimal import Decimal
from dataclasses import dataclass, field
from enum import Enum
import uuid
from collections import defaultdict, deque
import numpy as np

from core.engine.order_manager import OrderType, TimeInForce
from utils.helpers import get_timestamp, synchronized
from monitoring.metrics import MetricsCollector


class SignalType(Enum):
    """Signal type enumeration"""
    LONG = "long"
    SHORT = "short"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"
    CLOSE_ALL = "close_all"


class SignalStrength(Enum):
    """Signal strength levels"""
    WEAK = "weak"
    MEDIUM = "medium"
    STRONG = "strong"
    VERY_STRONG = "very_strong"


class StrategyType(Enum):
    """Strategy type categories"""
    DIRECTIONAL = "directional"
    MEAN_REVERSION = "mean_reversion"
    MOMENTUM = "momentum"
    ARBITRAGE = "arbitrage"
    MARKET_MAKING = "market_making"
    STATISTICAL = "statistical"
    ML_BASED = "ml_based"


class StrategyStatus(Enum):
    """Strategy status"""
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"


@dataclass
class Signal:
    """
    Trading signal generated by strategies
    
    Contains all information needed to execute a trade including
    entry/exit conditions, risk parameters, and metadata.
    """
    signal_id: str
    strategy_id: str
    symbol: str
    exchange: str
    signal_type: SignalType
    timestamp: datetime
    
    # Order parameters
    side: str  # "BUY" or "SELL"
    quantity: Decimal
    order_type: OrderType
    entry_price: Decimal
    
    # Signal strength and confidence
    strength: SignalStrength
    confidence: Decimal  # 0-1 confidence score
    expected_return: Decimal
    risk: Decimal
    
    # Risk management
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    time_limit: Optional[timedelta] = None
    
    # Order parameters
    time_in_force: TimeInForce = TimeInForce.GTC
    reduce_only: bool = False
    post_only: bool = False
    
    # Metadata
    model_predictions: Dict[str, Any] = field(default_factory=dict)
    market_conditions: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # Tracking
    created_at: datetime = field(default_factory=datetime.utcnow)
    executed: bool = False
    executed_at: Optional[datetime] = None
    execution_price: Optional[Decimal] = None
    
    @property
    def risk_reward_ratio(self) -> Optional[Decimal]:
        """Calculate risk/reward ratio"""
        if not self.stop_loss or not self.take_profit:
            return None
        
        risk = abs(self.entry_price - self.stop_loss)
        reward = abs(self.take_profit - self.entry_price)
        
        if risk == 0:
            return None
        
        return reward / risk
    
    @property
    def is_expired(self) -> bool:
        """Check if signal has expired"""
        if not self.time_limit:
            return False
        
        return datetime.utcnow() > self.created_at + self.time_limit
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary"""
        return {
            "signal_id": self.signal_id,
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "exchange": self.exchange,
            "signal_type": self.signal_type.value,
            "timestamp": self.timestamp.isoformat(),
            "side": self.side,
            "quantity": str(self.quantity),
            "order_type": self.order_type.value,
            "entry_price": str(self.entry_price),
            "strength": self.strength.value,
            "confidence": str(self.confidence),
            "expected_return": str(self.expected_return),
            "risk": str(self.risk),
            "stop_loss": str(self.stop_loss) if self.stop_loss else None,
            "take_profit": str(self.take_profit) if self.take_profit else None,
            "risk_reward_ratio": str(self.risk_reward_ratio) if self.risk_reward_ratio else None,
            "executed": self.executed
        }


@dataclass
class StrategyPerformance:
    """Strategy performance metrics"""
    strategy_id: str
    
    # Trade statistics
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    
    # P&L metrics
    total_pnl: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")
    unrealized_pnl: Decimal = Decimal("0")
    
    # Performance metrics
    win_rate: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    max_drawdown: Decimal = Decimal("0")
    
    # Signal quality
    signals_generated: int = 0
    signals_executed: int = 0
    average_confidence: float = 0.0
    
    # Timing
    first_trade: Optional[datetime] = None
    last_trade: Optional[datetime] = None
    
    # Recent performance
    recent_returns: deque = field(default_factory=lambda: deque(maxlen=100))
    
    def update_metrics(self) -> None:
        """Update calculated metrics"""
        if self.total_trades > 0:
            self.win_rate = self.winning_trades / self.total_trades
        
        if self.recent_returns:
            returns = list(self.recent_returns)
            if len(returns) > 1:
                self.sharpe_ratio = np.mean(returns) / np.std(returns) * np.sqrt(252)


@dataclass
class Strategy:
    """
    Base strategy configuration and state
    """
    strategy_id: str
    name: str
    strategy_type: StrategyType
    status: StrategyStatus = StrategyStatus.ACTIVE
    
    # Configuration
    symbols: List[str] = field(default_factory=list)
    exchanges: List[str] = field(default_factory=list)
    timeframes: List[str] = field(default_factory=list)
    
    # Risk parameters
    max_position_size: Decimal = Decimal("10000")
    max_positions: int = 5
    risk_per_trade: Decimal = Decimal("0.02")  # 2% risk per trade
    
    # Performance tracking
    performance: StrategyPerformance = field(default_factory=lambda: StrategyPerformance(strategy_id=""))
    
    # Strategy-specific parameters
    parameters: Dict[str, Any] = field(default_factory=dict)
    
    # Metadata
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)
    
    def __post_init__(self):
        """Initialize performance tracking"""
        self.performance.strategy_id = self.strategy_id


class StrategyCoordinator:
    """
    Coordinates all trading strategies
    
    Manages strategy lifecycle, signal generation, and performance tracking
    across multiple strategies operating simultaneously.
    """
    
    def __init__(
        self,
        config: Dict[str, Any],
        model_coordinator: Any,  # ModelCoordinator
        exchange_coordinator: Any  # ExchangeCoordinator
    ):
        self.config = config
        self.logger = logging.getLogger("AITHORIX.StrategyCoordinator")
        
        # Dependencies
        self.model_coordinator = model_coordinator
        self.exchange_coordinator = exchange_coordinator
        
        # Strategy registry
        self.strategies: Dict[str, Strategy] = {}
        self.strategy_instances: Dict[str, Any] = {}  # Actual strategy implementations
        
        # Signal management
        self.active_signals: Dict[str, Signal] = {}
        self.signal_history: deque = deque(maxlen=10000)
        self.signals_by_symbol: Dict[str, List[Signal]] = defaultdict(list)
        
        # Performance tracking
        self.metrics_collector = MetricsCollector()
        self.strategy_performance: Dict[str, StrategyPerformance] = {}
        
        # Configuration
        self.max_signals_per_symbol = config.get("max_signals_per_symbol", 3)
        self.signal_expiry_time = timedelta(minutes=config.get("signal_expiry_minutes", 5))
        self.min_confidence_threshold = Decimal(str(config.get("min_confidence", "0.7")))
        
        # State
        self._lock = asyncio.Lock()
        self.is_initialized = False
        self.is_running = False
        
        # Strategy factories
        self._strategy_factories: Dict[StrategyType, Callable] = {}
        
    async def initialize(self) -> None:
        """Initialize the strategy coordinator"""
        self.logger.info("Initializing Strategy Coordinator...")
        
        # Register built-in strategies
        await self._register_builtin_strategies()
        
        # Load configured strategies
        await self._load_configured_strategies()
        
        # Start background tasks
        asyncio.create_task(self._signal_management_loop())
        asyncio.create_task(self._performance_tracking_loop())
        
        self.is_initialized = True
        self.logger.info(f"Strategy Coordinator initialized with {len(self.strategies)} strategies")
    
    async def start(self) -> None:
        """Start all active strategies"""
        self.logger.info("Starting strategies...")
        self.is_running = True
        
        for strategy_id, strategy in self.strategies.items():
            if strategy.status == StrategyStatus.ACTIVE:
                try:
                    await self._start_strategy(strategy_id)
                    self.logger.info(f"Started strategy: {strategy.name}")
                except Exception as e:
                    self.logger.error(f"Failed to start strategy {strategy.name}: {e}")
                    strategy.status = StrategyStatus.ERROR
    
    async def stop(self) -> None:
        """Stop all strategies"""
        self.logger.info("Stopping strategies...")
        self.is_running = False
        
        for strategy_id in list(self.strategies.keys()):
            try:
                await self._stop_strategy(strategy_id)
            except Exception as e:
                self.logger.error(f"Error stopping strategy {strategy_id}: {e}")
    
    @synchronized
    async def generate_signals(
        self,
        market_state: Dict[str, Any],
        predictions: Dict[str, Any]
    ) -> List[Signal]:
        """Generate trading signals from all active strategies"""
        all_signals = []
        
        for strategy_id, strategy in self.strategies.items():
            if strategy.status != StrategyStatus.ACTIVE:
                continue
            
            try:
                # Get strategy instance
                strategy_instance = self.strategy_instances.get(strategy_id)
                if not strategy_instance:
                    continue
                
                # Generate signals for this strategy
                signals = await self._generate_strategy_signals(
                    strategy,
                    strategy_instance,
                    market_state,
                    predictions
                )
                
                # Validate and filter signals
                validated_signals = await self._validate_signals(signals, strategy)
                
                all_signals.extend(validated_signals)
                
            except Exception as e:
                self.logger.error(f"Error generating signals for {strategy.name}: {e}")
        
        # Apply global signal filters
        filtered_signals = await self._apply_global_filters(all_signals)
        
        # Store active signals
        for signal in filtered_signals:
            self.active_signals[signal.signal_id] = signal
            self.signals_by_symbol[signal.symbol].append(signal)
            self.signal_history.append(signal)
            
            # Update strategy performance
            strategy = self.strategies.get(signal.strategy_id)
            if strategy:
                strategy.performance.signals_generated += 1
        
        return filtered_signals
    
    async def _generate_strategy_signals(
        self,
        strategy: Strategy,
        strategy_instance: Any,
        market_state: Dict[str, Any],
        predictions: Dict[str, Any]
    ) -> List[Signal]:
        """Generate signals for a specific strategy"""
        signals = []
        
        # Filter market state for strategy's symbols
        strategy_market_state = {
            symbol: data
            for symbol, data in market_state.get("market_data", {}).items()
            if symbol in strategy.symbols
        }
        
        # Filter predictions for strategy
        strategy_predictions = {
            symbol: pred
            for symbol, pred in predictions.items()
            if symbol in strategy.symbols
        }
        
        # Call strategy's signal generation method
        if hasattr(strategy_instance, "generate_signals"):
            raw_signals = await strategy_instance.generate_signals(
                strategy_market_state,
                strategy_predictions,
                strategy.parameters
            )
            
            # Convert to Signal objects
            for raw_signal in raw_signals:
                signal = self._create_signal_from_raw(raw_signal, strategy)
                if signal:
                    signals.append(signal)
        
        return signals
    
    def _create_signal_from_raw(self, raw_signal: Dict[str, Any], strategy: Strategy) -> Optional[Signal]:
        """Create Signal object from raw strategy output"""
        try:
            # Determine signal type
            signal_type_str = raw_signal.get("signal_type", "long")
            signal_type = SignalType(signal_type_str)
            
            # Determine side based on signal type
            if signal_type in [SignalType.LONG, SignalType.CLOSE_SHORT]:
                side = "BUY"
            else:
                side = "SELL"
            
            # Create signal
            signal = Signal(
                signal_id=str(uuid.uuid4()),
                strategy_id=strategy.strategy_id,
                symbol=raw_signal["symbol"],
                exchange=raw_signal.get("exchange", strategy.exchanges[0]),
                signal_type=signal_type,
                timestamp=datetime.utcnow(),
                side=side,
                quantity=Decimal(str(raw_signal.get("quantity", "0"))),
                order_type=OrderType(raw_signal.get("order_type", "limit")),
                entry_price=Decimal(str(raw_signal["entry_price"])),
                strength=SignalStrength(raw_signal.get("strength", "medium")),
                confidence=Decimal(str(raw_signal.get("confidence", "0.5"))),
                expected_return=Decimal(str(raw_signal.get("expected_return", "0.01"))),
                risk=Decimal(str(raw_signal.get("risk", "0.01"))),
                stop_loss=Decimal(str(raw_signal["stop_loss"])) if "stop_loss" in raw_signal else None,
                take_profit=Decimal(str(raw_signal["take_profit"])) if "take_profit" in raw_signal else None,
                time_limit=timedelta(minutes=raw_signal.get("time_limit_minutes", 5)),
                model_predictions=raw_signal.get("model_predictions", {}),
                market_conditions=raw_signal.get("market_conditions", {}),
                metadata=raw_signal.get("metadata", {})
            )
            
            return signal
            
        except Exception as e:
            self.logger.error(f"Error creating signal from raw data: {e}")
            return None
    
    async def _validate_signals(self, signals: List[Signal], strategy: Strategy) -> List[Signal]:
        """Validate signals against strategy constraints"""
        validated = []
        
        for signal in signals:
            # Check confidence threshold
            if signal.confidence < self.min_confidence_threshold:
                self.logger.debug(f"Signal rejected: Low confidence {signal.confidence}")
                continue
            
            # Check position limits
            current_positions = len([
                s for s in self.active_signals.values()
                if s.strategy_id == strategy.strategy_id and s.symbol == signal.symbol and s.executed
            ])
            
            if current_positions >= strategy.max_positions:
                self.logger.debug(f"Signal rejected: Position limit reached for {signal.symbol}")
                continue
            
            # Check risk limits
            if signal.risk > strategy.risk_per_trade:
                self.logger.debug(f"Signal rejected: Risk {signal.risk} exceeds limit")
                continue
            
            # Check risk/reward ratio
            if signal.risk_reward_ratio and signal.risk_reward_ratio < Decimal("1.5"):
                self.logger.debug(f"Signal rejected: Poor risk/reward ratio {signal.risk_reward_ratio}")
                continue
            
            validated.append(signal)
        
        return validated
    
    async def _apply_global_filters(self, signals: List[Signal]) -> List[Signal]:
        """Apply global filters across all signals"""
        filtered = []
        
        # Group by symbol
        signals_by_symbol = defaultdict(list)
        for signal in signals:
            signals_by_symbol[signal.symbol].append(signal)
        
        # Apply per-symbol limits
        for symbol, symbol_signals in signals_by_symbol.items():
            # Check existing signals for symbol
            existing_count = len([
                s for s in self.active_signals.values()
                if s.symbol == symbol and not s.executed
            ])
            
            remaining_slots = self.max_signals_per_symbol - existing_count
            
            if remaining_slots <= 0:
                continue
            
            # Sort by confidence and take best signals
            symbol_signals.sort(key=lambda s: s.confidence, reverse=True)
            filtered.extend(symbol_signals[:remaining_slots])
        
        return filtered
    
    async def register_strategy(
        self,
        strategy_type: StrategyType,
        name: str,
        symbols: List[str],
        exchanges: List[str],
        parameters: Dict[str, Any]
    ) -> str:
        """Register a new strategy"""
        strategy_id = str(uuid.uuid4())
        
        strategy = Strategy(
            strategy_id=strategy_id,
            name=name,
            strategy_type=strategy_type,
            symbols=symbols,
            exchanges=exchanges,
            parameters=parameters
        )
        
        # Create strategy instance
        factory = self._strategy_factories.get(strategy_type)
        if factory:
            strategy_instance = factory(strategy_id, parameters)
            self.strategy_instances[strategy_id] = strategy_instance
        
        # Store strategy
        self.strategies[strategy_id] = strategy
        self.strategy_performance[strategy_id] = strategy.performance
        
        self.logger.info(f"Registered strategy: {name} ({strategy_id})")
        
        return strategy_id
    
    async def update_strategy_status(self, strategy_id: str, status: StrategyStatus) -> None:
        """Update strategy status"""
        strategy = self.strategies.get(strategy_id)
        if not strategy:
            raise ValueError(f"Strategy {strategy_id} not found")
        
        old_status = strategy.status
        strategy.status = status
        strategy.updated_at = datetime.utcnow()
        
        self.logger.info(f"Strategy {strategy.name} status changed: {old_status.value} -> {status.value}")
        
        # Handle status change
        if status == StrategyStatus.ACTIVE and old_status != StrategyStatus.ACTIVE:
            await self._start_strategy(strategy_id)
        elif status != StrategyStatus.ACTIVE and old_status == StrategyStatus.ACTIVE:
            await self._stop_strategy(strategy_id)
    
    async def mark_signal_executed(
        self,
        signal_id: str,
        execution_price: Decimal,
        execution_time: datetime
    ) -> None:
        """Mark a signal as executed"""
        signal = self.active_signals.get(signal_id)
        if not signal:
            return
        
        signal.executed = True
        signal.executed_at = execution_time
        signal.execution_price = execution_price
        
        # Update strategy performance
        strategy = self.strategies.get(signal.strategy_id)
        if strategy:
            strategy.performance.signals_executed += 1
        
        self.logger.info(f"Signal {signal_id} executed at {execution_price}")
    
    def get_active_signals(self, symbol: Optional[str] = None) -> List[Signal]:
        """Get active signals, optionally filtered by symbol"""
        if symbol:
            return [
                s for s in self.active_signals.values()
                if s.symbol == symbol and not s.executed and not s.is_expired
            ]
        
        return [
            s for s in self.active_signals.values()
            if not s.executed and not s.is_expired
        ]
    
    def get_strategy_performance(self, strategy_id: str) -> Optional[StrategyPerformance]:
        """Get performance metrics for a strategy"""
        return self.strategy_performance.get(strategy_id)
    
    def get_all_performance_metrics(self) -> Dict[str, Dict[str, Any]]:
        """Get performance metrics for all strategies"""
        metrics = {}
        
        for strategy_id, performance in self.strategy_performance.items():
            strategy = self.strategies.get(strategy_id)
            if strategy:
                metrics[strategy_id] = {
                    "name": strategy.name,
                    "type": strategy.strategy_type.value,
                    "status": strategy.status.value,
                    "total_trades": performance.total_trades,
                    "win_rate": performance.win_rate,
                    "total_pnl": float(performance.total_pnl),
                    "sharpe_ratio": performance.sharpe_ratio,
                    "signals_generated": performance.signals_generated,
                    "signals_executed": performance.signals_executed
                }
        
        return metrics
    
    async def _register_builtin_strategies(self) -> None:
        """Register built-in strategy factories"""
        # Register strategy type factories
        self._strategy_factories[StrategyType.MOMENTUM] = self._create_momentum_strategy
        self._strategy_factories[StrategyType.MEAN_REVERSION] = self._create_mean_reversion_strategy
        self._strategy_factories[StrategyType.ARBITRAGE] = self._create_arbitrage_strategy
        self._strategy_factories[StrategyType.ML_BASED] = self._create_ml_based_strategy
        
        self.logger.info("Registered built-in strategy factories")
    
    async def _load_configured_strategies(self) -> None:
        """Load strategies from configuration"""
        strategies_config = self.config.get("strategies", [])
        
        for strategy_config in strategies_config:
            try:
                strategy_id = await self.register_strategy(
                    strategy_type=StrategyType(strategy_config["type"]),
                    name=strategy_config["name"],
                    symbols=strategy_config["symbols"],
                    exchanges=strategy_config["exchanges"],
                    parameters=strategy_config.get("parameters", {})
                )
                
                # Set initial status
                if strategy_config.get("enabled", True):
                    await self.update_strategy_status(strategy_id, StrategyStatus.ACTIVE)
                
            except Exception as e:
                self.logger.error(f"Failed to load strategy {strategy_config.get('name')}: {e}")
    
    async def _start_strategy(self, strategy_id: str) -> None:
        """Start a strategy"""
        strategy_instance = self.strategy_instances.get(strategy_id)
        if strategy_instance and hasattr(strategy_instance, "start"):
            await strategy_instance.start()
    
    async def _stop_strategy(self, strategy_id: str) -> None:
        """Stop a strategy"""
        strategy_instance = self.strategy_instances.get(strategy_id)
        if strategy_instance and hasattr(strategy_instance, "stop"):
            await strategy_instance.stop()
        
        # Cancel active signals
        for signal in list(self.active_signals.values()):
            if signal.strategy_id == strategy_id and not signal.executed:
                self.active_signals.pop(signal.signal_id, None)
    
    async def _signal_management_loop(self) -> None:
        """Manage signal lifecycle"""
        while True:
            try:
                # Clean up expired signals
                expired_signals = []
                for signal_id, signal in self.active_signals.items():
                    if signal.is_expired and not signal.executed:
                        expired_signals.append(signal_id)
                
                for signal_id in expired_signals:
                    self.active_signals.pop(signal_id, None)
                    self.logger.debug(f"Removed expired signal: {signal_id}")
                
                # Clean up old executed signals
                cutoff_time = datetime.utcnow() - timedelta(hours=1)
                old_signals = []
                for signal_id, signal in self.active_signals.items():
                    if signal.executed and signal.executed_at and signal.executed_at < cutoff_time:
                        old_signals.append(signal_id)
                
                for signal_id in old_signals:
                    self.active_signals.pop(signal_id, None)
                
                await asyncio.sleep(30)  # Every 30 seconds
                
            except Exception as e:
                self.logger.error(f"Error in signal management loop: {e}")
                await asyncio.sleep(30)
    
    async def _performance_tracking_loop(self) -> None:
        """Track strategy performance"""
        while True:
            try:
                # Update performance metrics
                for strategy_id, performance in self.strategy_performance.items():
                    performance.update_metrics()
                
                # Log performance summary
                total_pnl = sum(p.total_pnl for p in self.strategy_performance.values())
                active_strategies = sum(1 for s in self.strategies.values() if s.status == StrategyStatus.ACTIVE)
                
                self.logger.info(f"Strategy performance - Active: {active_strategies}, "
                               f"Total P&L: {total_pnl}, "
                               f"Signals: {len(self.active_signals)}")
                
                await asyncio.sleep(300)  # Every 5 minutes
                
            except Exception as e:
                self.logger.error(f"Error in performance tracking loop: {e}")
                await asyncio.sleep(300)
    
    # Strategy factory methods
    
    def _create_momentum_strategy(self, strategy_id: str, parameters: Dict[str, Any]) -> Any:
        """Create momentum strategy instance"""
        # This would create actual momentum strategy
        return type('MomentumStrategy', (), {
            'generate_signals': lambda self, market_state, predictions, params: []
        })()
    
    def _create_mean_reversion_strategy(self, strategy_id: str, parameters: Dict[str, Any]) -> Any:
        """Create mean reversion strategy instance"""
        # This would create actual mean reversion strategy
        return type('MeanReversionStrategy', (), {
            'generate_signals': lambda self, market_state, predictions, params: []
        })()
    
    def _create_arbitrage_strategy(self, strategy_id: str, parameters: Dict[str, Any]) -> Any:
        """Create arbitrage strategy instance"""
        # This would create actual arbitrage strategy
        return type('ArbitrageStrategy', (), {
            'generate_signals': lambda self, market_state, predictions, params: []
        })()
    
    def _create_ml_based_strategy(self, strategy_id: str, parameters: Dict[str, Any]) -> Any:
        """Create ML-based strategy instance"""
        # This would create actual ML-based strategy
        return type('MLStrategy', (), {
            'generate_signals': lambda self, market_state, predictions, params: []
        })()
    
    def get_active_strategy_count(self) -> int:
        """Get count of active strategies"""
        return sum(1 for s in self.strategies.values() if s.status == StrategyStatus.ACTIVE)
    
    def get_status(self) -> Dict[str, Any]:
        """Get strategy coordinator status"""
        return {
            "running": self.is_running,
            "total_strategies": len(self.strategies),
            "active_strategies": self.get_active_strategy_count(),
            "active_signals": len(self.active_signals),
            "performance": {
                "total_pnl": float(sum(p.total_pnl for p in self.strategy_performance.values())),
                "total_trades": sum(p.total_trades for p in self.strategy_performance.values()),
                "average_win_rate": np.mean([p.win_rate for p in self.strategy_performance.values()]) if self.strategy_performance else 0
            }
        }